-- SQL Customer & Sales Analytics
-- Product Analysis


-- Q19. Find the top 10 products by revenue
SELECT
    product_id,
    product_name,
    SUM(amount) AS revenue
FROM orders
GROUP BY
    product_id,
    product_name
ORDER BY revenue DESC
LIMIT 10;


-- Q20. Find the highest-selling product in each category
WITH product_sales AS (
    SELECT
        category,
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        category,
        product_id,
        product_name
),
ranked_products AS (
    SELECT
        *,
        RANK() OVER(
            PARTITION BY category
            ORDER BY revenue DESC
        ) AS product_rank
    FROM product_sales
)
SELECT *
FROM ranked_products
WHERE product_rank = 1;


-- Q21. Find the top 3 products in each category
WITH product_sales AS (
    SELECT
        category,
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        category,
        product_id,
        product_name
),
ranked_products AS (
    SELECT
        *,
        DENSE_RANK() OVER(
            PARTITION BY category
            ORDER BY revenue DESC
        ) AS product_rank
    FROM product_sales
)
SELECT *
FROM ranked_products
WHERE product_rank <= 3;


-- Q22. Find total quantity sold by product
SELECT
    product_id,
    product_name,
    SUM(quantity) AS total_quantity
FROM orders
GROUP BY
    product_id,
    product_name
ORDER BY total_quantity DESC;


-- Q23. Find average order value by product
SELECT
    product_id,
    product_name,
    AVG(amount) AS average_order_value
FROM orders
GROUP BY
    product_id,
    product_name
ORDER BY average_order_value DESC;


-- Q24. Rank products within each category
WITH product_sales AS (
    SELECT
        category,
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        category,
        product_id,
        product_name
)
SELECT
    *,
    RANK() OVER(
        PARTITION BY category
        ORDER BY revenue DESC
    ) AS product_rank
FROM product_sales
ORDER BY category, product_rank;


-- Q25. Find total revenue by category
SELECT
    category,
    SUM(amount) AS total_revenue
FROM orders
GROUP BY category
ORDER BY total_revenue DESC;


-- Q26. Find the number of products sold in each category
SELECT
    category,
    COUNT(DISTINCT product_id) AS total_products
FROM orders
GROUP BY category
ORDER BY total_products DESC;


-- Q27. Find the highest revenue generated by a single product
WITH product_sales AS (
    SELECT
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        product_id,
        product_name
)
SELECT
    MAX(revenue) AS highest_product_revenue
FROM product_sales;


-- Q28. Find products whose revenue is greater than the
-- average product revenue
WITH product_sales AS (
    SELECT
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        product_id,
        product_name
)
SELECT
    product_id,
    product_name,
    revenue
FROM product_sales
WHERE revenue > (
    SELECT AVG(revenue)
    FROM product_sales
)
ORDER BY revenue DESC;


-- Q29. Find the lowest-selling products
WITH product_sales AS (
    SELECT
        product_id,
        product_name,
        SUM(amount) AS revenue
    FROM orders
    GROUP BY
        product_id,
        product_name
)
SELECT
    product_id,
    product_name,
    revenue
FROM product_sales
ORDER BY revenue ASC
LIMIT 10;


-- Q30. Find the number of orders for each product
SELECT
    product_id,
    product_name,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY
    product_id,
    product_name
ORDER BY total_orders DESC;
